name: Security Scanning

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Trivy vulnerability scanner (table format)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'

    - name: Set up Python for dependency check
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install safety for Python dependency check
      run: |
        pip install safety

    - name: Run Python Safety Check
      run: |
        cd backend
        safety check --json --output safety-report.json || echo "Safety check completed"

    - name: Set up Node.js for frontend security
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run npm audit for frontend
      run: |
        cd frontend
        npm audit --audit-level=moderate || echo "npm audit completed"

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          trivy-results.sarif
          backend/safety-report.json
        retention-days: 30